app_version: 0.18.3.4
categories:
- financial
description: Monero is a private, decentralized cryptocurrency that keeps your finances
  confidential and secure.
home: https://www.getmonero.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/monero/icons/icon.png
keywords:
- monero
- cryptocurrency
- blockchain
- privacy
lib_version: 2.1.14
lib_version_hash: 982057eeec3024ccecbeaa70e9ee59d948523a3b29d9fca6b39f127a42caa1cc
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: monero
screenshots: []
sources:
- https://www.getmonero.org
- https://github.com/sethforprivacy/simple-monerod-docker
- https://github.com/sethforprivacy/simple-monero-wallet-rpc-docker
title: Monero
train: community
version: 1.1.8
