app_version: 0.18.3.4
capabilities: []
categories:
- financial
description: Monero is a private, decentralized cryptocurrency that keeps your finances
  confidential and secure.
home: https://www.getmonero.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/monero/icons/icon.png
keywords:
- monero
- cryptocurrency
- blockchain
- privacy
lib_version: 2.1.15
lib_version_hash: e26cffb91766782c787867b379519f7407b1fed8450dce463cefa56340a41d84
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: monero
run_as_context:
- description: "Monero runs as root user. FIXME: update this"
  gid: 0
  group_name: root
  uid: 0
  user_name: root
screenshots: []
sources:
- https://www.getmonero.org
- https://github.com/sethforprivacy/simple-monerod-docker
- https://github.com/sethforprivacy/simple-monero-wallet-rpc-docker
title: Monero
train: community
version: 1.0.0
