images:
  monerod:
    repository: ghcr.io/sethforprivacy/simple-monerod
    tag: v0.18.3.4
  monero_wallet_rpc:
    repository: ghcr.io/sethforprivacy/simple-monero-wallet-rpc
    tag: v0.18.3.4
  # onion_monero_explorer:
  #   repository: ghcr.io/magicgrants/onion-monero-explorer
  #   tag: master-9050231

consts:
  monerod_container_name: monerod
  monero_wallet_rpc_container_name: monero_wallet_rpc
  onion_monero_explorer_container_name: onion_monero_explorer

  network:
    monerod_p2p_port: 18080
    monerod_rpc_port: 18081
    monerod_restricted_rpc_port: 18089
    monero_wallet_rpc_port: 18083
    # explorer_port: 18090

  volumes:
    bitmonero:
      type: volume
      volume_config:
        volume_name: bitmonero

    monero_wallet_rpc:
      type: volume
      volume_config:
        volume_name: monero_wallet_rpc
