app_version: 1.4.0
capabilities: []
categories:
- networking
description: Arti is an experimental Tor implementation written in Rust, and it is
  designed to be modular, reusable, and easy to audit.
home: https://tpo.pages.torproject.net/core/arti/
host_mounts: []
icon: https://media.sys.truenas.net/apps/arti/icons/icon.png
keywords:
- tor
- privacy
lib_version: 2.1.16
lib_version_hash: 488c896e0dc7d49e8023e527a0769bfb7cb97a29899fba058fcee81bd323212b
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: arti
run_as_context:
- description: Arti runs as non-root user.
  gid: 1000
  group_name: arti
  uid: 1000
  user_name: arti
screenshots: []
sources:
- https://tpo.pages.torproject.net/core/arti/
- https://github.com/MAGICGrants/arti-docker
title: Arti
train: community
version: 1.0.0
