resources:
  limits:
    cpus: 2.0
    memory: 4096
TZ: UTC

monero:
  ipv6_enabled: true
  node:
    enabled: true
    pruned: true
    logging: true
    ssl_enabled: true
    remote_node_url: http://192.168.255.101:18089
    additional_flags: []
  wallet:
    enabled: true
  explorer:
    enabled: false
  networking:
    tor_connections_enabled: true
    tor_ip: 192.168.255.101
    tor_port: 9150
    i2p_connections_enabled: false
    i2p_ip: 192.168.255.101
    i2p_port: 9150
    routing: tor

network:
  host_network: false
  monerod_p2p_port:
    bind_mode: published
    port_number: 18080
  monerod_rpc_port:
    bind_mode: published
    port_number: 18081
  monerod_restricted_rpc_port:
    bind_mode: published
    port_number: 18089
  wallet_rpc_port:
    bind_mode: ""
    port_number: 18083

ix_volumes:
  bitmonero: /opt/tests/mnt/bitmonero
  blockchain: /opt/tests/mnt/blockchain
  wallet: /opt/tests/mnt/wallet
  logs: /opt/tests/mnt/logs

storage:
  bitmonero:
    type: ix_volume
    ix_volume_config:
      dataset_name: bitmonero
      create_host_path: true
  blockchain:
    type: ix_volume
    ix_volume_config:
      dataset_name: blockchain
      create_host_path: true
  logs:
    type: ix_volume
    ix_volume_config:
      dataset_name: logs
      create_host_path: true
  wallet:
    type: ix_volume
    ix_volume_config:
      dataset_name: wallet
      create_host_path: true
  additional_storage: []
